-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here
vim.api.nvim_set_keymap("n", ";", ":", { desc = "" })
vim.api.nvim_set_keymap("n", "<leader>0", ":%y+<CR>", { desc = "Yank All!" })
vim.api.nvim_set_keymap("n", "<leader>1", ":TimerStart 1h<enter>", { desc = "Pomo 1h" })
vim.api.nvim_set_keymap("n", "<leader>2", ":TimerStart 30m<enter>", { desc = "Pomo 30m" })
vim.api.nvim_set_keymap("n", "<leader>3", ":Glow<cr>", { desc = "Glow" })
vim.api.nvim_set_keymap("n", "<leader>n", ":ASToggle<CR>", {})
-- vim.api.nvim_set_keymap("n", "<leader>4", ":Yazi<cr>", { desc = "Yazi" })
-- vim.api.nvim_set_keymap("n", "<Leader>uj", ":IBLToggle<Enter>", { desc = "Toggle IBL" })
vim.api.nvim_set_keymap("n", "<Leader>o", ":ObsidianSearch<Enter>", { desc = "Obsidian Vault" })
vim.api.nvim_set_keymap("n", "<Leader>z", ":ZenMode<Enter>", { desc = "Zen Mode" })
vim.keymap.set("n", "<leader>h", "<cmd>ToggleNeoColumn<cr>", { noremap = true, silent = true })
-- vim.api.nvim_set_keymap("n", "<Leader>6", ":%!fold -s -w 80<CR>", { desc = "Reformat Text: 80 cols" })
vim.api.nvim_set_keymap("n", "<Leader>.", "`.", { desc = "Last Insert" })
vim.api.nvim_set_keymap("i", "<C-d>", "<C-o>dw", { desc = "" })
-- vim.api.nvim_set_keymap("i", "<C-k>", "<C-o>dd", { desc = ""})
vim.api.nvim_set_keymap("n", "<F12>", ":Outline<CR>", { desc = "" })
vim.api.nvim_set_keymap("n", "<C-v>", "p", { desc = "" })
vim.api.nvim_set_keymap("i", "<C-v>", "<C-o>p", { desc = "" })
vim.api.nvim_set_keymap("v", "<C-c>", "y", { noremap = true, desc = "" })
-- vim.api.nvim_set_keymap("n", "<C-Enter>", "O", { desc = ""})
-- vim.api.nvim_set_keymap("n", "<Enter>", "o", { desc = ""})
vim.api.nvim_set_keymap("i", "<C-c>", "<C-o>yy", { desc = "" })
vim.api.nvim_set_keymap("n", "<ScrollWheelDown>", "5j", { desc = "" })
vim.api.nvim_set_keymap("n", "<ScrollWheelUp>", "5k", { desc = "" })
vim.keymap.set({ "i" }, "<S-Right>", "<Del>", { desc = "" })
vim.keymap.set({ "i" }, "<S-Left>", "<C-h>", { desc = "" })
vim.keymap.set({ "i" }, "<S-Down>", "<C-o>v", { desc = "" })
vim.keymap.set({ "i" }, "<S-Up>", "<C-o>cas", { desc = "" })
vim.keymap.set({ "n" }, "<S-Right>", "a", { desc = "" })
vim.keymap.set({ "n" }, "<S-Left>", "i", { desc = "" })
vim.keymap.set({ "n" }, "<S-Down>", "v%", { desc = "" })
vim.keymap.set({ "n" }, "<S-Up>", "daw", { desc = "" })
vim.keymap.set({ "v" }, "<S-Right>", "e", { desc = "" })
vim.keymap.set({ "v" }, "<S-Left>", "b", { desc = "" })
vim.keymap.set({ "v" }, "<S-Down>", "j", { desc = "" })
vim.keymap.set({ "v" }, "<S-Up>", "k", { desc = "" })
vim.keymap.set({ "n" }, "<C-Up>", "-", { desc = "" })
vim.keymap.set({ "i" }, "<C-Up>", "<C-o>-", { desc = "" })
vim.keymap.set({ "n" }, "<C-Down>", "+", { desc = "" })
vim.keymap.set({ "i" }, "<C-Down>", "<C-o>+", { desc = "" })
vim.keymap.set({ "i" }, "<C-a>", "<C-w>", { desc = "" })
vim.keymap.set({ "n", "v", "i" }, "<C-s>", "<C-[>:wa<CR>", { desc = "" })
vim.keymap.set("n", "<C-Right>", "e", { desc = "" })
vim.keymap.set("i", "<C-Right>", "<C-[>ea", { desc = "" })
vim.keymap.set("n", "<C-Left>", "b", { desc = "" })
vim.keymap.set("i", "<C-Left>", "<C-[>bi", { desc = "" })
-- vim.keymap.set("n", "<S-z>", "ZZ", { desc = ""})
-- vim.keymap.set("n", "<leader>k", "gcc", { desc = ""})
vim.api.nvim_set_keymap("n", "p", ':lua require("nvim-clean-paste").custom_paste()<CR>', { silent = true })
vim.keymap.set("i", "<down>", "<C-o>gj")
vim.keymap.set("i", "<up>", "<C-o>gk")
vim.keymap.set("n", "<C-z>", "u")
vim.keymap.set("i", "<C-z>", "<C-o>u")
vim.keymap.set("n", "<C-y>", "<C-r>", { desc = "" })
vim.keymap.set("i", "<C-y>", "<C-o><C-r>", { desc = "" })
vim.api.nvim_set_keymap("n", "<F2>", ":NvimCmpToggle<CR>", { silent = true })
