-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here
vim.api.nvim_set_keymap("n", ";", ":", { noremap = true })
vim.api.nvim_set_keymap("n", "<leader>0", ":%y+<CR>", { noremap = true })
vim.api.nvim_set_keymap("i", "<C-d>", "<C-o>dw", { noremap = true })
vim.api.nvim_set_keymap("n", "<C-j>", "a<CR>", { noremap = true })
vim.api.nvim_set_keymap("n", "<F12>", ":Outline<enter>", { noremap = true })
vim.api.nvim_set_keymap("n", "<C-v>", "p", { noremap = true })
vim.api.nvim_set_keymap("i", "<C-v>", "<C-o>p", { noremap = true })
vim.api.nvim_set_keymap("n", "<C-c>", "yy", { noremap = true })
-- vim.api.nvim_set_keymap("n", "<C-Enter>", "O", { noremap = true })
-- vim.api.nvim_set_keymap("n", "<Enter>", "o", { noremap = true })
vim.api.nvim_set_keymap("i", "<C-c>", "<C-o>yy", { noremap = true })
vim.api.nvim_set_keymap("n", "<ScrollWheelDown>", "<C-d>", { noremap = true })
vim.api.nvim_set_keymap("n", "<ScrollWheelUp>", "<C-u>", { noremap = true })
vim.keymap.set({ "i" }, "<S-Right>", "<Del>", { noremap = true })
vim.keymap.set({ "n" }, "<S-Right>", "a", { noremap = true })
vim.keymap.set({ "i" }, "<S-Left>", "<C-h>", { noremap = true })
vim.keymap.set({ "n" }, "<S-Left>", "i", { noremap = true })
vim.keymap.set({ "i" }, "<S-Down>", "<C-[>:wa<CR>", { noremap = true })
vim.keymap.set({ "i" }, "<S-Up>", "<C-o>cas", { noremap = true })
vim.keymap.set({ "n" }, "<S-Up>", "daw", { noremap = true })
vim.keymap.set({ "i" }, "<C-a>", "<C-w>", { noremap = true })
vim.keymap.set({ "n" }, "<S-Down>", ":wa<Esc>v%", { noremap = true })
vim.keymap.set({ "n" }, "<C-Up>", "-", { noremap = true })
vim.keymap.set({ "i" }, "<C-Up>", "<C-o>-", { noremap = true })
vim.keymap.set({ "n" }, "<C-Down>", "+", { noremap = true })
vim.keymap.set({ "i" }, "<C-Down>", "<C-o>+", { noremap = true })
-- vim.keymap.set({ "n", "v" }, "<C-s>", "s", { noremap = true })
vim.keymap.set("n", "<C-Right>", "e", { noremap = true })
vim.keymap.set("i", "<C-Right>", "<C-[>ea", { noremap = true })
vim.keymap.set("n", "<C-Left>", "b", { noremap = true })
-- vim.keymap.set("n", "<S-z>", "ZZ", { noremap = true })
-- vim.keymap.set("n", "<leader>k", "gcc", { noremap = true })
vim.keymap.set("i", "<C-Left>", "<C-[>bi", { noremap = true })
vim.api.nvim_set_keymap("n", "<Leader>3", ":IBLToggle<Enter>", { noremap = true })
vim.api.nvim_set_keymap("n", "<Leader>4", ":ZenMode<Enter>", { noremap = true })
vim.api.nvim_set_keymap(
  "n",
  "p",
  ':lua require("nvim-clean-paste").custom_paste()<CR>',
  { noremap = true, silent = true }
)
vim.api.nvim_set_keymap("n", "<leader>1", ":TimerStart 1h<enter>", { noremap = true })
vim.api.nvim_set_keymap("n", "<leader>2", ":TimerStart 30m<enter>", { noremap = true })
vim.keymap.set("i", "<down>", "<C-o>gj")
vim.keymap.set("i", "<up>", "<C-o>gk")
vim.keymap.set("n", "<C-z>", "u")
vim.keymap.set("i", "<C-z>", "<C-o>u")
vim.keymap.set("n", "<C-y>", "<C-r>")
vim.keymap.set("i", "<C-y>", "<C-o><C-r>")
-- vim.api.nvim_set_keymap("n", "<F2>", ":NvimCmpToggle<CR>", { noremap = true, silent = true })
